### PR TITLE
upgraded to ember 13.3 and fixed deprecations

### LINKED ISSUE #34: Deprecation "A property of... was modified inside the didInsertElement hook." after upgrading to ember 1.13
Hi,
I am getting the following deprecation warning from the component after upgrading to ember 1.13 
>A property of... was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation.

### PR DESCRIPTION
**Pull request by djvoa12**
- Upgraded to Ember 1.13.4
- Upgraded to Ember-Cli 1.13.1
- Upgraded to QUnit to 0.4.1 (ember-test-helpers 0.5.1)
- Upgraded few other packages
- Replaced old syntax with ES6 syntax
- Fixed upcoming `Ember.keys` deprecation (1.13.3) among other deprecations since Ember 1.12
- Included override properties from `ember-in-viewport`
  - Changed from `didInsertElement` to `didInitAttrs` due to performance warnings

fixes #34

### CODE REVIEW

**Comment by twokul** [comment]
@djvoa12 travis is angry

File: addon/components/lazy-background-image.js [hunk 1]
```diff
@@ -15,10 +14,11 @@ export default Component.extend(InViewportMixin, ImageLoadMixin, LazyImageMixin,
 
   classNames: ['lazy-background-image'],
 
-  _setupAttributes: function() {
+  _setupAttributes() {
     const component = this;
+    const keys = Object.keys(component);
```
Comment (fsmanuel) [inline addon/components/lazy-background-image.js]: We should fallback to `Ember.keys`:
```
const keys = Object.keys || Ember.keys;

keys(component).forEach((key) => {
});
```

Comment (djvoa12) [inline addon/components/lazy-background-image.js]: word

File: .travis.yml [hunk 2]
```diff
@@ -9,6 +9,16 @@ cache:
   directories:
     - node_modules
 
+env:
+  matrix:
+    - EMBER_TRY_SCENARIO=ember-release
+    - EMBER_TRY_SCENARIO=ember-canary
```
Comment (fsmanuel) [inline .travis.yml]: ember-beta

File: tests/dummy/config/environment.js [hunk 3]
```diff
@@ -40,7 +40,7 @@ module.exports = function(environment) {
     ENV.baseURL = '/';
     ENV.locationType = 'none';
 
-    ENV.EmberENV.RAISE_ON_DEPRECATION = true;
+    ENV.EmberENV.RAISE_ON_DEPRECATION = false;
```
Comment (fsmanuel) [inline tests/dummy/config/environment.js]: i guess it's better to have deprecations turned on to fix problems before they make their way into apps

**Comment by fsmanuel** [comment]
@djvoa12 I added some comments :+1:

File: .travis.yml (hunk 2 above)
Comment (djvoa12) [inline .travis.yml]: added

File: addon/mixins/lazy-image.js [hunk 4]
```diff
@@ -1,15 +1,26 @@
 import Ember from 'ember';
 import Cache from '../lib/cache';
 
-const { on, get, set, Mixin, computed } = Ember;
+const { on, get, set, Mixin, computed, setProperties } = Ember;
 const dasherize = Ember.String.dasherize;
 
 export default Mixin.create({
+  viewportOptionsOveride: on('didInsertElement', function() {
```
Comment (fsmanuel) [inline addon/mixins/lazy-image.js]: do we have to change that to `didRender` or something?

Comment (twokul) [inline addon/mixins/lazy-image.js]: I don't think so because it shouldn't trigger template re-render? worth looking into

File: tests/dummy/config/environment.js (hunk 3 above)
Comment (djvoa12) [inline tests/dummy/config/environment.js]: changed
